name: Something
on:
    push:
        branches: 
            - main

jobs:
    convert_nb_to_html:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - uses: r-lib/actions/setup-r@v1
              with:
                  r-version: '3.5.3'
            - run: python3 -m pip install notebook
            - run: R -e "install.packages(\"IRkernel\")"
            - run: R -e "IRkernel::installspec()"
            - run: jupyter nbconvert --execute --to html trabajo.ipynb
