name: Something
on:
    push:
        branches: [master]

jobs:
    convert_nb_to_html:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - run: python3 -m pip install notebook
            - run: jupyter nbconvert --execute --to html trabajo.ipynb
